# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme


theme: jekyll-theme-minimal
title: Shiyan Wei
description: |
  I am a Finance Ph.D. Candidate at the Paul Merage School of Business, University of California, Irvine.
  My research focuses on institutional investors and asset pricing through the lens of industrial organization and demand systems. I also study the impact of the data economy and learning on the financial market and the demographic and housing market.
